import random
from faker import Faker
fake = Faker()


class FakeFlightPerson:
    def __init__(self, orderID, name, address, birthday, email, segment, chanellname, citycode, countrycode, airlinecode, reservationid, origin, destination, amount, ticketprice):
        self.orderID = orderID
        self.name = name
        self.address = address
        self.birthday = birthday
        self.email = email
        self.segment = segment
        self.chanellname = chanellname
        self.citycode = citycode
        self.countrycode = countrycode
        self.airlinecode = airlinecode
        self.reservationid = reservationid
        self.origin = origin
        self.destination = destination
        self.amount = amount
        self.ticketprice = ticketprice



def CreateFakeFlightPerson():   
    chanellNameList = ['XTatil',
                       'Obilet',
                       'Fixbilet',
                       'Enuygun',
                       'Skycanner',
                       'bilet.com',
                       'Tatilsepeti',
                       'None']
    AirlineList = [
"Aegean Airlines",
"Aer Lingus",
"Aeroflot",
"Aerolineas Argentinas",
"Aeromexico",
"Air Arabia",
"Air Astana",
"Air Austral",
"Air Baltic",
"Air Belgium",
"Air Canada",
"Air Caraibes",
"Air China",
"Air Corsica",
"Air Dolomiti",
"Air Europa",
"Air France",
"Air India",
"Air India Express",
"Air Macau",
"Air Malta",
"Air Mauritius",
"Air Namibia",
"Air New Zealand",
"Air North",
"Air Seoul",
"Air Serbia",
"Air Tahiti Nui",
"Air Transat",
"Air Vanuatu",
"AirAsia",
"AirAsia X",
"Aircalin",
"Alaska Airlines",
"Alitalia",
"Allegiant",
"American Airlines",
"ANA",
"Asiana",
"Austrian",
"Avianca",
"Azerbaijan Hava Yollary",
"Azores Airlines",
"Azul",
"Bamboo Airways",
"Bangkok Airways",
"British Airways",
"Brussels Airlines",
"Caribbean Airlines",
"Cathay Dragon",
"Cathay Pacific",
"Cayman Airways",
"CEBU Pacific Air",
"China Airlines",
"China Eastern",
"China Southern",
"Condor",
"Copa Airlines",
"Croatia Airlines",
"Czech Airlines",
"Delta",
"easyJet",
"Edelweiss Air",
"Egyptair",
"Emirates",
"Ethiopian Airlines",
"Etihad",
"Eurowings",
"EVA Air",
"Fiji Airways",
"Finnair",
"flydubai",
"FlyOne",
"French bee",
"Frontier",
"Garuda Indonesia",
"Gol",
"Gulf Air",
"Hainan Airlines",
"Hawaiian Airlines",
"Helvetic Airways",
"HK Express",
"Hong Kong Airlines",
"Iberia",
"Icelandair",
"IndiGo Airlines",
"InterJet",
"Japan Airlines",
"Jeju Air",
"Jet2",
"JetBlue",
"Jetstar",
"Jin Air",
"Kenya Airways",
"KLM",
"Korean Air",
"Kulula",
"La Compagnie",
"LATAM",
"Lion Airlines",
"LOT Polish Airlines",
"Lufthansa",
"Luxair",
"Malaysia Airlines",
"Mango",
"Middle East Airlines",
"Nok Air",
"Nordwind Airlines",
"Norwegian Air International",
"Norwegian Air Shuttle",
"Norwegian Air Sweden",
"Norwegian Air UK",
"Oman Air",
"Pakistan International Airlines",
"Peach",
"Pegasus Airlines",
"Philippine Airlines",
"Porter",
"Qantas",
"Qatar Airways",
"Regional Express",
"Rossiya - Russian Airlines",
"Royal Air Maroc",
"Royal Brunei",
"Royal Jordanian",
"RwandAir",
"Ryanair",
"S7 Airlines",
"SAS",
"Saudia",
"Scoot Airlines",
"Shanghai Airlines",
"Silkair",
"Silver",
"Singapore Airlines",
"Skylanes",
"South African Airways",
"Southwest",
"SpiceJet",
"Spirit",
"Spring Airlines",
"Spring Japan",
"SriLankan Airlines",
"Sun Country",
"Sunclass Airlines",
"Sunwing",
"SWISS",
"Swoop",
"TAAG",
"TACA",
"TAP Portugal",
"THAI",
"tigerair Australia",
"Transavia Airlines",
"TUI UK",
"TUIfly",
"Tunis Air",
"Turkish Airlines",
"Ukraine International",
"United",
"Ural Airlines",
"UTair Aviation",
"Uzbekistan Airways",
"Vietnam Airlines",
"Virgin Atlantic",
"Virgin Australia",
"Vistara",
"Viva Aerobus",
"Volaris",
"Volotea",
"Vueling Airlines",
"WestJet",
"Wizzair",
"Xiamen Airlines"
    ]

    person = FakeFlightPerson(
        orderID=fake.passport_number(),
        name=fake.name(),
        address=fake.address(),
        birthday=fake.date_of_birth(),
        email=fake.ascii_email(),
        segment=random.choice(['Economy', 'Premium Economy', 'Business', 'First', 'Suit']),
        chanellname=random.choice(chanellNameList),
        citycode=fake.city(),
        countrycode=fake.country_code(),
        airlinecode=random.choice(AirlineList),
        reservationid=fake.random.randint(0, 999999999),
        origin=''.join([fake.city(), fake.country_code()]),
        destination=''.join([fake.city(), fake.country_code()]),
        amount=fake.random.randint(0, 200),
        ticketprice=fake.random.randint(0, 1000),
    )

    result = {'orderID': person.orderID,
        'name': person.name,
        'address': person.address,
        'birthday': person.birthday,
        'email': person.email,
        'segment': person.segment,
        'chanellname': person.chanellname,
        'citycode': person.citycode,
        'countrycode': person.countrycode,
        'airlinecode': person.airlinecode,
        'reservationid': person.reservationid,
        'origin': person.origin,
        'destination': person.destination,
        'amount': person.amount,
        'ticketprice': person.ticketprice
    }
    return result



